### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by ghost** [Hybridmax/G92X_Mystery_Kernel#1]
When i start building the kernel I get a error saying

Makefile.fwinst:45: target '/lib/firmware/tsp_stm/stm_z1.fw' given more than once in the same rule
Makefile.fwinst:45: target '/lib/firmware/abov/abov_valley.fw' given more than once in the same rule

**Comment by ton-An** [comment]
This should help you:
https://github.com/exynos7420/android_kernel_samsung_exynos7420/commit/0f792af5d696745f3f1884fee563d13a74dcefd5

**Comment by ghost** [comment]
Its fixed thanks 😋😋

_Sent from my Samsung SM-G925F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
